# define a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryman
  template:
    metadata:
      labels:
        app: deliveryman
    spec:
      containers:
        - image: dmohorcic/microservice-deliveryman:1.2.1-SNAPSHOT
          name: deliveryman
          env:
              # from api/resources/config.yaml
              # kumuluzee -> datasources -> 0th element -> connection-url
            - name: KUMULUZEE_ENV_NAME
              value: prod
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com:5432/lyjcsikn
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lyjcsikn
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deliveryman-elephantsql
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

# define connection to pod
apiVersion: v1
kind: Service
metadata:
  name: deliveryman-service # can be random
spec:
  # ClusterIP for ms that call each other -> available only within cluster
  # LoadBalancer for public IP
  # LoadPort
  type: ClusterIP
  ports:
      # this is outside port, we map server:port (server is in Deployment)
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: deliveryman # select pod