kumuluzee:
  name: deliveryman-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/DeliverymanMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/deliveryman-metadata
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    servlet:
      mapping: /health
      enabled: true
    checks:
      data-source-health-check:
        type: both
        jndi-name: jdbc/DeliverymanMetadataDS
      disk-space-health-check:
        type: both
        threshold: 10000000 # 10MB

rest-properties:
  maintenance-mode: false
  broken: false
