name: Build, package, and push

on: workflow_dispatch
  #push:
  #  branches: [main]
  #pull_request:
  #  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: YYYY-MM-DD-HH-mm-ss
          utcOffset: "+02:00"

      - name: Extract version
        id: version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "pom.xml"
          xpath: "/*[namespace-uri()='http://maven.apache.org/POM/4.0.0' and local-name()='project']/*[namespace-uri()='http://maven.apache.org/POM/4.0.0' and local-name()='version']/text()"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile_with_maven_build
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microservice-deliveryman:${{ steps.version.outputs.info }}
