name: Test version extraction

on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "pom.xml"
          xpath: "//*[local-name()='project']/*[local-name()='version']/text()"
      
      - name: Print version
        run: |
          echo "${{ steps.version.outputs.info }}"