name: Test version extraction

on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: version
        uses: mavrosxristoforos/get-xml-info@1.1.1
        with:
          xml-file: "pom.xml"
          xpath: "/*[namespace-uri()='http://maven.apache.org/POM/4.0.0' and local-name()='project']/*[namespace-uri()='http://maven.apache.org/POM/4.0.0' and local-name()='version']/text()"
      
      - name: Print version
        run: |
          echo ${{ steps.version.outputs.info }}